let appState;
const $ = s => document.querySelector(s);
const escapeHtml = s => String(s).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(path, options={}) { const r = await fetch(path, {headers:{'Content-Type':'application/json'}, ...options}); return r.json(); }
function render() { renderTasks(); renderChat(); if (appState.profile) { const name = appState.profile.name; $('#profileName').textContent = name; $('#greetingName').textContent = name; $('#avatar').textContent = name.slice(0, 1); } }
function renderTasks() { const list = $('#taskList'); list.innerHTML = appState.tasks.map(t => { const mins = Math.floor(t.elapsed / 60); const secs = String(t.elapsed % 60).padStart(2,'0'); const status = t.status === 'done' ? 'done' : ''; const button = t.status === 'active' ? `<button class="task-btn pause" data-action="pause" data-id="${t.id}">暂停</button>` : t.status === 'done' ? '<span class="task-time">已完成 ✓</span>' : `<button class="task-btn" data-action="start" data-id="${t.id}">开始专注</button>`; return `<div class="task ${status} ${t.status === 'active' ? 'active':''}"><div class="task-row"><span class="task-check">${t.status === 'done' ? '✓':''}</span><span class="task-title">${escapeHtml(t.title)}</span><span class="task-period">${escapeHtml(t.period)}</span></div><div class="task-foot"><span>◷ ${t.duration} 分钟</span><span class="task-time">${t.status === 'active' ? `　已专注 ${mins}:${secs}` : ''}</span>${button}</div></div>`; }).join(''); document.querySelectorAll('[data-action]').forEach(b => b.onclick = async () => { appState = await api(`/api/tasks/${b.dataset.id}/${b.dataset.action}`, {method:'POST'}); render(); toast(b.dataset.action === 'start' ? '已经开始，慢慢来就好 ✦' : '已暂停，去休息一下吧'); }); }
function renderChat() { $('#chat').innerHTML = appState.messages.slice(-4).map(m => `<div class="bubble ${m.role}">${escapeHtml(m.text)}</div>`).join(''); $('#chat').scrollTop = $('#chat').scrollHeight; }
async function send(text) { if (!text.trim()) return; $('#message').value=''; const result = await api('/api/chat',{method:'POST',body:JSON.stringify({text})}); appState=result.state; render(); }
function toast(text) { const el=$('#toast'); el.textContent=text; el.classList.add('show'); setTimeout(()=>el.classList.remove('show'),2200); }
$('#sendBtn').onclick=()=>send($('#message').value); $('#message').onkeydown=e=>{if(e.key==='Enter')send(e.target.value)}; document.querySelectorAll('.quick button').forEach(b=>b.onclick=()=>send(b.dataset.text));
$('#addBtn').onclick=async()=>{const title=prompt('想把哪件事放进今天？'); if(title) { const r=await api('/api/tasks',{method:'POST',body:JSON.stringify({title})}); appState=r.state; render(); toast('已经放进今天的计划啦'); }};
$('#profileBtn').onclick=async()=>{const current=appState.profile?.name || ''; const name=prompt('给自己取一个昵称吧', current); if(name && name.trim() !== current) { appState=await api('/api/profile',{method:'POST',body:JSON.stringify({name})}); render(); toast('昵称已更新，欢迎回来 ✦'); }};
$('#micBtn').onclick=()=>{ const SpeechRecognition=window.SpeechRecognition||window.webkitSpeechRecognition; if(!SpeechRecognition) return toast('当前浏览器暂不支持语音识别'); const recognition=new SpeechRecognition(); recognition.lang='zh-CN'; recognition.onstart=()=>toast('我在听，请说吧…'); recognition.onresult=e=>send(e.results[0][0].transcript); recognition.start(); };
setInterval(async()=>{ if(appState?.tasks.some(t=>t.status==='active')) { appState=await api('/api/state'); renderTasks(); } },1000);
(async()=>{appState=await api('/api/state');render();})();
